# Generated by Django 5.1.7 on 2025-06-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='shared_with_user_email',
            field=models.CharField(default='default@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
