# Generated by Django 5.1.7 on 2025-06-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_files', '0002_sharedfile_shared_with_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='file_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='file_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
