# Generated by Django 5.1.7 on 2025-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_files', '0003_sharedfile_file_name_sharedfile_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='owner_user_email',
            field=models.CharField(default='asdasda@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
