# Generated by Django 5.1.7 on 2025-07-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_files', '0004_sharedfile_owner_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='can_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
