# Generated by Django 5.1.7 on 2025-06-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.CharField(max_length=255)),
                ('bucket_name', models.CharField(max_length=255)),
                ('file_key', models.TextField()),
                ('shared_with_user_id', models.CharField(max_length=255)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
