# Generated by Django 5.1.7 on 2025-06-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_files_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedFile',
        ),
    ]
