# Generated by Django 5.1.7 on 2025-07-04 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='ID del usuario que realizó la acción', max_length=255)),
                ('user_email', models.CharField(help_text='Email del usuario que realizó la acción', max_length=255)),
                ('action', models.CharField(choices=[('UPLOAD', 'Subir'), ('DOWNLOAD', 'Descargar'), ('UPDATE', 'Modificar'), ('DELETE', 'Eliminar'), ('SHARE', 'Compartir'), ('UNSHARE', 'Dejar de compartir')], help_text='Acción realizada', max_length=20)),
                ('file_key', models.TextField(help_text='Clave/ruta del archivo en S3')),
                ('file_name', models.CharField(help_text='Nombre del archivo', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('bucket_name', models.CharField(help_text='Nombre del bucket de S3', max_length=255)),
                ('owner_user_id', models.CharField(blank=True, help_text='ID del propietario del archivo (si es compartido)', max_length=255, null=True)),
                ('owner_user_email', models.CharField(blank=True, help_text='Email del propietario del archivo (si es compartido)', max_length=255, null=True)),
                ('shared_with_user_id', models.CharField(blank=True, help_text='ID del usuario con quien se compartió', max_length=255, null=True)),
                ('shared_with_user_email', models.CharField(blank=True, help_text='Email del usuario con quien se compartió', max_length=255, null=True)),
                ('old_file_name', models.CharField(blank=True, help_text='Nombre anterior del archivo (para operaciones de actualización)', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la acción')),
                ('success', models.BooleanField(default=True, help_text='Indica si la operación fue exitosa')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la operación falló', null=True)),
            ],
            options={
                'db_table': 'audit_file_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='audit_file__user_id_ad91e6_idx'), models.Index(fields=['action', 'timestamp'], name='audit_file__action_5aa7d6_idx'), models.Index(fields=['file_key'], name='audit_file__file_ke_e7fa2b_idx'), models.Index(fields=['bucket_name', 'timestamp'], name='audit_file__bucket__84fbea_idx')],
            },
        ),
        migrations.CreateModel(
            name='FolderLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='ID del usuario que realizó la acción', max_length=255)),
                ('user_email', models.CharField(help_text='Email del usuario que realizó la acción', max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Modificar'), ('DELETE', 'Eliminar')], help_text='Acción realizada', max_length=20)),
                ('folder_key', models.TextField(help_text='Clave/ruta de la carpeta en S3')),
                ('folder_name', models.CharField(help_text='Nombre de la carpeta', max_length=255)),
                ('bucket_name', models.CharField(help_text='Nombre del bucket de S3', max_length=255)),
                ('old_folder_name', models.CharField(blank=True, help_text='Nombre anterior de la carpeta (para operaciones de actualización)', max_length=255, null=True)),
                ('parent_folder', models.CharField(blank=True, help_text='Carpeta padre', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la acción')),
                ('success', models.BooleanField(default=True, help_text='Indica si la operación fue exitosa')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la operación falló', null=True)),
            ],
            options={
                'db_table': 'audit_folder_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='audit_folde_user_id_cf1b9d_idx'), models.Index(fields=['action', 'timestamp'], name='audit_folde_action_96a799_idx'), models.Index(fields=['folder_key'], name='audit_folde_folder__7273d4_idx'), models.Index(fields=['bucket_name', 'timestamp'], name='audit_folde_bucket__040a11_idx')],
            },
        ),
    ]
