# Generated by Django 5.1.7 on 2025-07-04 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SHARE', 'Share'), ('UNSHARE', 'Unshare')], help_text='Action performed', max_length=20),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='bucket_name',
            field=models.CharField(help_text='S3 bucket name', max_length=255),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the operation failed', null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='file_key',
            field=models.TextField(help_text='File key/path in S3'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='file_name',
            field=models.CharField(help_text='File name', max_length=255),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='old_file_name',
            field=models.CharField(blank=True, help_text='Previous file name (for update operations)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='owner_user_email',
            field=models.CharField(blank=True, help_text='Email of the file owner (if shared)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='owner_user_id',
            field=models.CharField(blank=True, help_text='ID of the file owner (if shared)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='shared_with_user_email',
            field=models.CharField(blank=True, help_text='Email of the user the file was shared with', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='shared_with_user_id',
            field=models.CharField(blank=True, help_text='ID of the user the file was shared with', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='success',
            field=models.BooleanField(default=True, help_text='Indicates if the operation was successful'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the action'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser user agent', null=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='user_email',
            field=models.CharField(help_text='Email of the user who performed the action', max_length=255),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='user_id',
            field=models.CharField(help_text='ID of the user who performed the action', max_length=255),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], help_text='Action performed', max_length=20),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='bucket_name',
            field=models.CharField(help_text='S3 bucket name', max_length=255),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the operation failed', null=True),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='folder_key',
            field=models.TextField(help_text='Folder key/path in S3'),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='folder_name',
            field=models.CharField(help_text='Folder name', max_length=255),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='old_folder_name',
            field=models.CharField(blank=True, help_text='Previous folder name (for update operations)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='parent_folder',
            field=models.CharField(blank=True, help_text='Parent folder', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='success',
            field=models.BooleanField(default=True, help_text='Indicates if the operation was successful'),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the action'),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser user agent', null=True),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='user_email',
            field=models.CharField(help_text='Email of the user who performed the action', max_length=255),
        ),
        migrations.AlterField(
            model_name='folderlog',
            name='user_id',
            field=models.CharField(help_text='ID of the user who performed the action', max_length=255),
        ),
    ]
