from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, permissions
from .models import TOTPSecret
import pyotp
from django.conf import settings
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi
import qrcode
import io
import boto3
from django.core.files.base import ContentFile

# Create your views here.

class GenerateTOTPSecretView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Generate the otpauth_url to set up TOTP (2FA) in an authentication app.",
        responses={
            200: openapi.Response(
                description="otpauth_url generated correctly",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'otpauth_url': openapi.Schema(type=openapi.TYPE_STRING, description="URL for authentication apps"),
                        'message': openapi.Schema(type=openapi.TYPE_STRING, description="Information message")
                    }
                )
            ),
            401: 'Unauthorized',
        },
        tags=['TOTP']
    )
    def post(self, request):
        user_email = request.user.email
        # Search if it already exists
        totp_obj, created = TOTPSecret.objects.get_or_create(user_email=user_email)
        if created:
            # Generate new secret key
            secret = pyotp.random_base32()
            totp_obj.secret = secret
            totp_obj.save()
        else:
            secret = totp_obj.secret
        # Generate URI for apps like Google Authenticator
        totp_uri = pyotp.totp.TOTP(secret).provisioning_uri(name=user_email, issuer_name="SecureRepository")
        return Response({
            'secret': secret,
            'otpauth_url': totp_uri,
            'message': 'Scan this QR in your authentication app.'
        })

class ValidateTOTPView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Validate a TOTP code generated by an authentication app.",
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            required=['code'],
            properties={
                'code': openapi.Schema(type=openapi.TYPE_STRING, description="6-digit TOTP code")
            }
        ),
        responses={
            200: openapi.Response(
                description="Valid TOTP code",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'message': openapi.Schema(type=openapi.TYPE_STRING)
                    }
                )
            ),
            400: openapi.Response(
                description="Invalid TOTP code",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'error': openapi.Schema(type=openapi.TYPE_STRING)
                    }
                )
            ),
            401: 'Unauthorized',
        },
        tags=['TOTP']
    )
    def post(self, request):
        user_email = request.user.email
        code = request.data.get('code')
        try:
            totp_obj = TOTPSecret.objects.get(user_email=user_email)
        except TOTPSecret.DoesNotExist:
            return Response({'error': 'No TOTP secret for this user.'}, status=status.HTTP_404_NOT_FOUND)
        totp = pyotp.TOTP(totp_obj.secret)
        if totp.verify(code):
            return Response({'message': 'Valid TOTP code.'})
        else:
            return Response({'error': 'Invalid TOTP code.'}, status=status.HTTP_400_BAD_REQUEST)

class SendTOTPQRView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Generate the TOTP QR and send it by email using AWS SES to the authenticated user's email.",
        responses={
            200: openapi.Response(
                description="QR sent correctly",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'message': openapi.Schema(type=openapi.TYPE_STRING)
                    }
                )
            ),
            400: openapi.Response(
                description="Error in the request",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'error': openapi.Schema(type=openapi.TYPE_STRING)
                    }
                )
            ),
            401: 'Unauthorized',
        },
        tags=['TOTP']
    )
    def post(self, request):
        return Response({'error': 'Email sending functionality disabled.'}, status=status.HTTP_400_BAD_REQUEST)
